import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const db = new PrismaClient();

const products = [
  // iPhones
  {
    nameEn: "iPhone 16e",
    nameAr: "آيفون 16e",
    sku: "MC-IPH16E",
    brand: "Apple",
    categoryLevel1: "Phones",
    categoryLevel2: "iPhones",
    sellingPrice: 935000,
    costPrice: 820000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2025/02/iPhone_16e_White_PDP_Image_Position_1__en-ME-768x768.jpg",
    highlights: "A16 Bionic chip, 6.1-inch Super Retina XDR display, 48MP camera, USB-C",
  },
  {
    nameEn: "iPhone 16",
    nameAr: "آيفون 16",
    sku: "MC-IPH16",
    brand: "Apple",
    categoryLevel1: "Phones",
    categoryLevel2: "iPhones",
    sellingPrice: 1055000,
    costPrice: 930000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2024/09/iPhone_16_Ultramarine_PDP_Image_Position_1__en-ME-768x768.jpg",
    highlights: "A18 chip, 6.1-inch display, 48MP Fusion camera, Camera Control button",
  },
  {
    nameEn: "iPhone 16 Plus",
    nameAr: "آيفون 16 بلس",
    sku: "MC-IPH16PLUS",
    brand: "Apple",
    categoryLevel1: "Phones",
    categoryLevel2: "iPhones",
    sellingPrice: 1205000,
    costPrice: 1065000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2024/09/iPhone_16_Plus_Ultramarine_PDP_Image_Position_1__en-ME-768x768.jpg",
    highlights: "A18 chip, 6.7-inch display, all-day battery life, 48MP camera",
  },
  {
    nameEn: "iPhone 16 Pro",
    nameAr: "آيفون 16 برو",
    sku: "MC-IPH16PRO",
    brand: "Apple",
    categoryLevel1: "Phones",
    categoryLevel2: "iPhones",
    sellingPrice: 1360000,
    costPrice: 1200000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2024/09/iPhone_16_Pro_Desert_Titanium_PDP_Image_Position_1__en-ME-scaled.jpg",
    highlights: "A18 Pro chip, 6.3-inch ProMotion display, 48MP Fusion + 12MP Ultra Wide + 5x Telephoto",
  },
  {
    nameEn: "iPhone 16 Pro Max",
    nameAr: "آيفون 16 برو ماكس",
    sku: "MC-IPH16PROMAX",
    brand: "Apple",
    categoryLevel1: "Phones",
    categoryLevel2: "iPhones",
    sellingPrice: 1680000,
    costPrice: 1490000,
    commissionPct: 5,
    mainImage: "https://mcenter-iraq.com/wp-content/uploads/2024/09/iPhone-16-Pro-Max-600x352.webp",
    highlights: "A18 Pro chip, 6.9-inch ProMotion display, 5x Telephoto, 4K 120fps Dolby Vision",
  },
  // iPads
  {
    nameEn: "iPad (10th generation)",
    nameAr: "آيباد الجيل العاشر",
    sku: "MC-IPAD10",
    brand: "Apple",
    categoryLevel1: "Tablets",
    categoryLevel2: "iPad",
    sellingPrice: 405000,
    costPrice: 355000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2023/09/iPad_10.9_inch_Wi-Fi_Silver_PDP_Image_Position-1b_EN-768x768.jpg",
    highlights: "A14 Bionic, 10.9-inch Liquid Retina, 12MP Ultra Wide front camera, USB-C",
  },
  {
    nameEn: "iPad (A16)",
    nameAr: "آيباد A16",
    sku: "MC-IPADA16",
    brand: "Apple",
    categoryLevel1: "Tablets",
    categoryLevel2: "iPad",
    sellingPrice: 500000,
    costPrice: 440000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2025/03/iPad_A16_WiFi_Blue_PDP_Image_Position_1__ar-SA-768x768.jpg",
    highlights: "A16 chip, 10.9-inch Liquid Retina, landscape front camera, USB-C",
  },
  {
    nameEn: "iPad mini (A17 Pro)",
    nameAr: "آيباد ميني A17 برو",
    sku: "MC-IPADMINI7",
    brand: "Apple",
    categoryLevel1: "Tablets",
    categoryLevel2: "iPad",
    sellingPrice: 720000,
    costPrice: 635000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2025/03/iPad_mini_Space_Gray_PDP_Image_Position_2_WiFi__en-ME-768x768.jpg",
    highlights: "A17 Pro chip, 8.3-inch Liquid Retina, Apple Intelligence, Apple Pencil Pro",
  },
  {
    nameEn: "iPad Air 11-inch (M3)",
    nameAr: "آيباد اير 11 انش M3",
    sku: "MC-IPADAIRM3-11",
    brand: "Apple",
    categoryLevel1: "Tablets",
    categoryLevel2: "iPad",
    sellingPrice: 885000,
    costPrice: 780000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2025/03/iPad_Air_11-inch_M3_WiFi_Purple_PDP_Image_Position_1__ar-SA-768x768.jpg",
    highlights: "M3 chip, 11-inch Liquid Retina, Apple Intelligence, 12MP front camera",
  },
  {
    nameEn: "iPad Air 13-inch (M3)",
    nameAr: "آيباد اير 13 انش M3",
    sku: "MC-IPADAIRM3-13",
    brand: "Apple",
    categoryLevel1: "Tablets",
    categoryLevel2: "iPad",
    sellingPrice: 1170000,
    costPrice: 1035000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2025/03/iPad_Air_13-inch_M3_WiFi_Purple_PDP_Image_Position_1__ar-SA-768x768.jpg",
    highlights: "M3 chip, 13-inch Liquid Retina, large display for creative work",
  },
  // MacBooks
  {
    nameEn: "MacBook Air 13-inch (M4)",
    nameAr: "ماك بوك اير 13 انش M4",
    sku: "MC-MBAM4-13",
    brand: "Apple",
    categoryLevel1: "Laptops",
    categoryLevel2: "MacBook",
    sellingPrice: 1410000,
    costPrice: 1245000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2025/03/MacBook_Air_13-inch_M4_Sky_Blue_PDP_Image_Position_1__ar-SA-scaled.jpg",
    highlights: "M4 chip, 13.6-inch Liquid Retina, 18-hour battery, fanless design",
  },
  {
    nameEn: "MacBook Air 15-inch (M4)",
    nameAr: "ماك بوك اير 15 انش M4",
    sku: "MC-MBAM4-15",
    brand: "Apple",
    categoryLevel1: "Laptops",
    categoryLevel2: "MacBook",
    sellingPrice: 1760000,
    costPrice: 1555000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2025/03/MacBook_Air_15-inch_M4_Sky_Blue_PDP_Image_Position_1__ar-SA-scaled.jpg",
    highlights: "M4 chip, 15.3-inch Liquid Retina, 18-hour battery, 1080p FaceTime camera",
  },
  // AirPods
  {
    nameEn: "AirPods 4",
    nameAr: "ايربودز 4",
    sku: "MC-AIRPODS4",
    brand: "Apple",
    categoryLevel1: "Audio",
    categoryLevel2: "AirPods",
    sellingPrice: 200000,
    costPrice: 175000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2024/09/AirPods_4_PDP_Image_Position_1__en-ME-768x768.jpg",
    highlights: "H2 chip, personalized Spatial Audio, USB-C charging case, 30-hour total battery",
  },
  {
    nameEn: "AirPods 4 with Active Noise Cancellation",
    nameAr: "ايربودز 4 مع إلغاء الضوضاء",
    sku: "MC-AIRPODS4ANC",
    brand: "Apple",
    categoryLevel1: "Audio",
    categoryLevel2: "AirPods",
    sellingPrice: 265000,
    costPrice: 232000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2024/09/AirPods_4_with_Active_Noise_Cancellation_PDP_Image_Position_1__en-ME-768x768.jpg",
    highlights: "H2 chip, Active Noise Cancellation, Transparency mode, MagSafe charging",
  },
  {
    nameEn: "AirPods Max",
    nameAr: "ايربودز ماكس",
    sku: "MC-AIRPODSMAX",
    brand: "Apple",
    categoryLevel1: "Audio",
    categoryLevel2: "AirPods",
    sellingPrice: 775000,
    costPrice: 685000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2024/09/AirPods_Max_2024_Starlight_PDP_Image_Position_1__en-ME-768x768.jpg",
    highlights: "H2 chip, premium over-ear headphones, 20-hour ANC battery, USB-C",
  },
  // Apple Watch
  {
    nameEn: "Apple Watch SE (2nd generation)",
    nameAr: "ساعة آبل SE الجيل الثاني",
    sku: "MC-WATCHSE2",
    brand: "Apple",
    categoryLevel1: "Wearables",
    categoryLevel2: "Apple Watch",
    sellingPrice: 345000,
    costPrice: 303000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2024/09/APPLE_1-44-768x768.jpg",
    highlights: "S8 chip, crash detection, heart rate sensor, swimproof, 18-hour battery",
  },
  {
    nameEn: "Apple Watch Ultra 2",
    nameAr: "ساعة آبل الترا 2",
    sku: "MC-WATCHULTRA2",
    brand: "Apple",
    categoryLevel1: "Wearables",
    categoryLevel2: "Apple Watch",
    sellingPrice: 1110000,
    costPrice: 980000,
    commissionPct: 5,
    mainImage: "https://www.icenter-iraq.com/wp-content/uploads/2024/09/APPLE_1-38-768x768.jpg",
    highlights: "S9 chip, 49mm titanium case, 60-hour battery, precision GPS, depth gauge",
  },
];

async function main() {
  const passwordHash = await bcrypt.hash("mcenter17", 12);

  const vendor = await db.vendor.upsert({
    where: { email: "mcenter@mobile.iq" },
    create: {
      reference: "VEN-MCENTER",
      name: "M Center",
      email: "mcenter@mobile.iq",
      passwordHash,
      phone: "+9647701234567",
      companyLocation: "Baghdad, Iraq",
      joinedAt: new Date(),
      accountManager: "",
      deliveryMechanism: "company",
    },
    update: { passwordHash },
  });
  console.log(`Vendor created: ${vendor.email} (id: ${vendor.id})`);

  let count = 0;
  for (const p of products) {
    await db.product.upsert({
      where: { sku: p.sku },
      create: {
        vendorId: vendor.id,
        nameEn: p.nameEn,
        nameAr: p.nameAr,
        nameKu: "",
        highlights: p.highlights,
        description: "",
        sku: p.sku,
        brand: p.brand,
        categoryLevel1: p.categoryLevel1,
        categoryLevel2: p.categoryLevel2,
        mainImage: p.mainImage,
        sellingPrice: p.sellingPrice,
        costPrice: p.costPrice,
        commissionPct: p.commissionPct,
        status: "published",
      },
      update: {
        nameEn: p.nameEn,
        nameAr: p.nameAr,
        mainImage: p.mainImage,
        sellingPrice: p.sellingPrice,
        costPrice: p.costPrice,
      },
    });
    count++;
    console.log(`  + ${p.nameEn} — ${p.sellingPrice.toLocaleString()} IQD`);
  }
  console.log(`\nDone. ${count} products added for M Center.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => db.$disconnect());
